<div class="row">
    <div class="col-md-6">
        <h1><?=$this->record->subject;?></h1>
    </div>
    <div class="col-md-6">
        <a style="margin-right: 5px;" class="btn btn-default pull-right" href="<?=$this->url(array('action'=>'index'))?>">
            <i class="glyphicon glyphicon-arrow-left"></i> Back to Messages</a>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-condensed table-striped">
        <tbody>
            <tr>
                <td style="width:10%">Date:</td>
                <td style="width:90%;"><?=$this->record->created_at->format('m/d/Y g:ia');?></td>
            </tr>
            <tr>
                <td style="width:10%">From:</td>
                <td style="width:90%;">
                <?php 
                 if ($this->record->origin_user) {
                   if(\Ia\Config::get('anonymous_messages')) {
                    echo($this->record->origin_user->first_name.' '.$this->record->origin_user->last_name[0]);
                   } else {
                     echo($this->record->origin_user->first_name.' '.$this->record->origin_user->last_name.' ('.$this->record->origin_user->email_address.')');
                   }
                 } else {
                   '<em>System</em>';
                 }?>
                 </td>
            </tr>
            <tr>
                <td style="width:10%">To:</td>
                <td style="width:90%;">
                    <?=$this->record->getRecipientUserName();?> (<?=$this->record->getRecipientEmailAddress();?>)
                </td>
            </tr>  
            <tr>
                <td style="width:10%">Subject:</td>
                <td style="width:90%;"><?=$this->record->subject;?></td>
            </tr> 
            <tr>
                <td style="width:10%"></td>
                <td style="width:90%;">
                    <?php if($this->record->link && $this->acl($this->record->link) && $this->acl(null,'message_follow-link')):?>
                    <a href="<?=$this->url(array('action'=>'follow-link'));?>"><i class="<?=($this->record->follow_link_icon) ? $this->record->follow_link_icon : 'glyphicon glyphicon-link'?>"></i> <?=($this->record->follow_link_text) ? $this->record->follow_link_text : 'Follow Link';?></a><br />
                    <?php endif; ?>
                    <?php foreach($this->record->getAttachmentFullPaths() as $full_path): ?>
                        <?php $parts = explode(DIRECTORY_SEPARATOR,$full_path); ?>
                        <a href="<?=$this->fullPathToUrl($full_path);?>" target="_blank"><i class="<?=($this->record->follow_link_icon) ? $this->record->follow_link_icon : 'glyphicon glyphicon-link'?>"></i> <?=array_pop($parts);?></a><br />
                    <?php endforeach; ?>
                </td>
            </tr>                
        </tbody>
    </table>
    <div class="well">
        <?php if(!($this->record->format) || $this->record->format==\Ia\Entity\Message::FORMAT_TEXT): ?>
        <p><?=nl2br($this->record->message);?></p>
        <?php else: ?>
        <p><?=($this->record->message);?></p>
        <?php endif; ?>
    </div>
</div>
