<?php
//my_pagination_control.phtml
if ($this->pageCount && $this->pageCount>1): ?>
<div class="pagination paginationControl pagination-left">
    <ul class="pagination">
        <?php if (isset($this->previous)): ?>
            <li class="first"><a href="<?php echo $this->url(array('page' => $this->first)); ?>"><?php echo $this->first; ?></a></li>
        <?php endif; ?>
        <?php foreach ($this->pagesInRange as $page):
            $class = '';
            if($page == $this->current)
                $class = 'active';
            if(($this->first < $page) && ($page < $this->last) || $page == $this->current): 
            ?>
            <li class="<?php echo $class; ?>"><a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>
            <?php
            endif;
        endforeach;
        ?>
        <?php if (isset($this->next)): ?>
            <li class="last"><a href="<?php echo $this->url(array('page' => $this->last)); ?>"><?php echo $this->last; ?></a></li>
        <?php endif; ?>
    </ul>
    <div>Displaying results <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
    of <?php echo $this->totalItemCount; ?></div>
</div>
<?php endif; ?>