<?php
$this->headScript()->captureStart();
?>
$(document).ready(function(){
var hasValues = 0;
$('td input.search').each(function(){
  $(this).css('width',$(this).parent().width() + 'px');
  if($(this).val()!='')
    hasValues = 1;
});
if(hasValues==0)
    $('tr#search').hide();
});
<?php
$this->headScript()->captureEnd();
?>

<?php if(!\Ia\Config::get('set_headings_in_layout') || !\Ia\Config::get('set_index_actions_in_layout')): ?>
<div class="row">
    <div class="col-md-6">
    <?php if(!\Ia\Config::get('set_headings_in_layout')): ?>
        <h1><?=ucwords($this->plural)?></h1>
    <?php endif; ?>
    </div>
    <div class="col-md-6">
    <?php 
    if(!\Ia\Config::get('set_index_actions_in_layout')):
    foreach($this->indexActions as $indexAction):
        if($this->acl(null,null,$indexAction['request'])): 
        ?>
            <a style="margin-left: 5px;" href="<?=$this->url($indexAction['request'],null,true)?>" class="pull-right <?=$indexAction['btnClass'];?>">
                <i class="<?=$indexAction['iconClass'];?>"></i> <?=$indexAction['label'];?></a>
        <?php
        endif;
    endforeach; 
    endif;
    ?>
    </div>
</div>
<?php endif; ?>

<div class="row">
    <?php if(sizeof($this->filterWidgets)>0 && !$this->horizontal_filters): ?>
    <div class="col-md-3">
        <div class="well" style="width:100%;overflow:hidden;">
        <?php foreach($this->filterWidgets as $filterWidget): ?>
            <?php foreach($filterWidget as $viewHelper=>$params): ?>
            <div style="margin-bottom:5px;"><?=call_user_func(array($this, $viewHelper), $params)?></div>
            <?php endforeach; ?>
        <?php endforeach; ?>
        </div>
    </div>
    <?php elseif(sizeof($this->filterWidgets)>0): ?>
        <?php foreach($this->filterWidgets as $filterWidget): ?>
            <?php foreach($filterWidget as $viewHelper=>$params): ?>
            <div class="col-md-3" style="margin-bottom:5px;"><?=call_user_func(array($this, $viewHelper), $params)?></div>
            <?php endforeach; ?>
        <?php endforeach; ?>
        <div class="col-md-12"><hr /></div>
        </div><div class="row">
    <?php endif; ?>

    <?php if(sizeof($this->filterWidgets)>0 && !$this->horizontal_filters): ?>
    <div class="col-md-9">
    <?php else: ?>
    <div class="col-md-12">
    <?php endif; ?>

    <?php if (count($this->paginator)): ?>

    <?php 
    if(isset($this->preGridHelpers) && is_array($this->preGridHelpers)):
        foreach($this->preGridHelpers as $viewHelper=>$params): ?>
            <?php $params['paginator'] = $this->paginator; ?>
            <div style="margin-bottom:5px;"><?=call_user_func(array($this, $viewHelper), $params)?></div>
        <?php endforeach;         
    endif;
    ?>    
    
    <?php if($this->bulkActions): ?>
        <div class="bulkActions well" style="float:left;width:100%">
        <p class="numSelectedNotice"><span class="numSelected">0</span> <?=ucwords($this->plural); ?> Selected</p>
        <?php foreach($this->bulkActions as $key=>$bulkAction): ?>
            <div class="bulkAction" id="bulkAction-<?=$key?>">
            <?php echo $this->renderIndexAction($bulkAction,null,'btn'); ?>
            </div>
        <?php endforeach; ?>
        </div>        
    <?php endif; ?>    
    
    <form method="post" id="searchForm">
        <div class="table-responsive">
        <table class="table table-condensed table-striped">
            <thead>
                <?php if(sizeof($this->bulkActions)>0): ?>
                <th><input type="checkbox" class="selectAll" /></th>
                <?php endif; ?>
                <?php foreach($this->columns as $key=>$title): ?>
                <th><?=$this->sortColumn($key,$title,$this->order);?></th>
                <?php endforeach; ?>
                <?php $num_action_cols = 0; ?>
                <?php if(isset($this->actions)): ?>
                    <?php foreach($this->actions as $action): ?>
                        <?php $num_action_cols++; ?>
                        <th class="action<?=$action['label']?>"><?=$action['label']?></th>
                    <?php endforeach;?>
                <?php else: ?>
                    <?php $num_action_cols = 3; ?>
                    <th>View</th>
                    <th>Edit</th>
                    <th>Delete</th>
                <?php endif; ?>
                <th><a onclick="$('#search').toggle()" class="pointer"><i class="glyphicon glyphicon-search"></i></a></th>
            </thead>
            <tr id="search">
                <?php if(sizeof($this->bulkActions)>0): ?>
                <td></td>
                <?php endif; ?>
                <?php foreach($this->columns as $key=>$title): ?>
                <td><input class="search form-control" name="search[<?=$key?>]" type="text" style="width:0px;" value="<?=(isset($this->params['search'][$key])) ? $this->params['search'][$key] : ''?>" /></td>
                <?php endforeach; ?>
                <td colspan="<?=$num_action_cols+1?>">
                    <input type="hidden" name="noSave" value="1" />
                    <input type="hidden" class="resetFilters" name="resetFilters" value="0" />
                    <button class="btn btn-primary">Search</button>
                    <button class="btn btn-default" onclick="$('form#searchForm input').val('');$('input.resetFilters').val(1);">Reset</button>
                </td>                
            </tr>
        <?php $showColumns = array(); ?>
        <?php foreach ($this->paginator as $item): 
            $this->record = $item; ?>
          <tr>
            <?php if(sizeof($this->bulkActions)>0): ?>
            <td><input type="checkbox" name="ids[]" value="<?=$item->id?>" /></td>
            <?php endif; ?>          
            <?php foreach($this->columns as $key=>$title): ?>
                <td>
                <? 
                $value = (is_array($item) && isset($item[$key])) ? $item[$key] : $this->getDoctrineEntityValue($item,$key,$this->relations);
                if(isset($this->formats) && isset($this->formats[$key])){
                    echo $this->{$this->formats[$key][0]}($value);
                } else {
                    echo $value;
                }
                ?>
                </td>
            <?php endforeach; ?>   
            <?php if(isset($this->actions)): ?>
                <?php foreach($this->actions as $action): 
                    $renderedAction = $this->renderIndexAction($action,$item);
                    if(!isset($showColumns[$action['label']]) && $renderedAction): ?>
                        <?php $showColumns[$action['label']] = true; ?>
                    <?php endif; ?>
                    <td class="action<?=$action['label']?>">
                        <?php echo $renderedAction; ?>
                    </td>
                <?php endforeach; ?>
            <?php else: ?>       
            <td>
                <a href="<?=$this->url(array('action'=>'view','id'=>$item->id))?>" title="View <?=ucwords($this->singular)?>"><i class="glyphicon glyphicon-eye-open"></i></a>
            </td>
            <td>
                <a href="<?=$this->url(array('action'=>'update','id'=>$item->id))?>" title="Update <?=ucwords($this->singular)?>"><i class="glyphicon glyphicon-pencil"></i></a>
            </td>
            <td>
                <a onclick="return confirm('Are you sure you want to permanently delete this record?');" href="<?=$this->url(array('action'=>'delete','id'=>$item->id))?>" title="Delete Job"><i class="glyphicon glyphicon-trash"></i></a>
            </td>
            <?php endif; ?>
            <td></td>
           </tr>
        <?php endforeach; ?>
        </table>
        </div>
        </form>
        <?php echo $this->paginationControl($this->paginator,
                                            'Sliding',
                                            '_pagination.phtml'); ?>         

        <?=$this->perPage($this->perPage)?>
        <a href="<?=$this->url(array('noSave'=>1,'format'=>'excel','perPage'=>-1))?>" class="btn btn-default"><i class="icon-list-alt"></i> Export to Excel</a>

        <?php 
        if(isset($this->postGridHelpers) && is_array($this->postGridHelpers)):
            foreach($this->postGridHelpers as $viewHelper=>$params): ?>
                <?php $params['paginator'] = $this->paginator; ?>
                <div style="margin-bottom:5px;"><?=call_user_func(array($this, $viewHelper), $params)?></div>
            <?php endforeach;         
        endif;
        ?>          

    <?php else: ?>
        <p>There are no <?=($this->plural)?> matching this criteria.  <a href="<?
        echo $this->url(array('resetFilters'=>true))?>">Search Again</a></p>
    <?php endif; ?>
    
    </div>
</div>

<?php $this->headStyle()->captureStart(); ?>
<?php foreach($this->actions as $action): ?>
    <?php if(!isset($showColumns[$action['label']])): ?>
        td.action<?=$action['label'];?>,th.action<?=$action['label'];?> {
            display:none;
        }
    <?php endif; ?>
<?php endforeach; ?>
<?php $this->headStyle()->captureEnd(); ?>
