<div class="row">
    <div class="col-md-6">
        <h1>View <?=ucwords($this->singular)?> #<?=$this->record->id?></h1>
    </div>
    <div class="col-md-6">
        <?php
        $module = ($this->params['module']=='default') ? '' : $this->params['module'].'_';
        $resource_prefix = $module.$this->params['controller'].'_';
        if($this->acl(null,$resource_prefix.'update')):
        ?>    
        <a class="btn btn-warning pull-right" href="<?=$this->url(array('action'=>'update'))?>"><i class="glyphicon glyphicon-pencil"></i> Edit this <?=ucwords($this->singular)?></a>
        <?php endif; 
        ?>
        <div class="pull-right" style="margin-right:5px">
            <?=$this->backButton();?>
        </div>
    </div>
</div>

<table class="table table-condensed table-striped">
    <?php foreach($this->detailColumns as $key=>$title): ?>
    <tr>
        <td><?=$title?></td>
        <td><?php
            $value = $this->getDoctrineEntityValue($this->record,$key,$this->relations);
            if(isset($this->formats) && isset($this->formats[$key])){                
                if(is_object($this->formats[$key][0])){
                    $this->formats[$key][0]->setView($this);
                    $parts = explode('_',get_class($this->formats[$key][0]));
                    $function_name = lcfirst(array_pop($parts));
                    echo $this->formats[$key][0]->{$function_name}($value);
                } else {
                    echo $this->{$this->formats[$key][0]}($value);
                }
            } else {
                echo $value;
            }
        ?></td>
    </tr>
    <?php endforeach; ?> 
</table>