<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title> <?=\Ia\Config::get('title');?> </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="//<?=$_SERVER['HTTP_HOST']?>/css/bootstrap.css" rel="stylesheet">
    <link href="css/bootstrap.css" rel="stylesheet">
    <?php echo $this->headStyle(); ?>
    <?php echo $this->headLink(); ?>
  </head>
  <?php if($this->autoPrint): ?><body onload="window.print()"><?php else: ?><body><?php endif; ?>
    <div class="container">
        <?=$this->layout()->content ?>
    </div> <!-- /container -->
  </body>
</html>
