<h1>Application Error</h1>
<h2><?php echo $this->message ?></h2>

<?php if (isset($this->exception)): ?>
<h3>Exception information:</h3>
<p>
  <b>Message:</b> <?php echo $this->exception->getMessage() ?>
</p>

<h3>Stack trace:</h3>
<pre><?php echo $this->exception->getTraceAsString() ?>
</pre>

<h3>Request Parameters:</h3>
<pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
</pre>

<h3>$_SERVER Dump:</h3>
<pre><?=print_r($_SERVER,1);?></pre>

<?php endif ?>