<div class="row">
    <div class="span6">
        <h1>View <?=ucwords($this->singular)?> #<?=$this->record->id?></h1>
    </div>
    <div class="span6">
        <a class="btn pull-right" href="<?=$this->url(array('action'=>'update'))?>"><i class="icon-pencil"></i> Edit this <?=ucwords($this->singular)?></a>
        <a style="margin-right: 5px;" class="btn pull-right" href="<?=$this->url(array('action'=>'index'))?>"><i class="icon-arrow-left"></i> Back to <?=ucwords($this->plural)?> List</a>
    </div>
</div>

<table class="table table-condensed table-striped">
    <?php foreach($this->detailColumns as $key=>$title): ?>
    <tr>
        <td><?=$title?></td>
        <td><?=$this->getDoctrineEntityValue($this->record,$key,$this->relations);?></td>
    </tr>
    <?php endforeach; ?> 
    <tr>
        <td>Data</td>
        <td><pre><?=print_r(unserialize($this->record->data),1)?></pre></td>
    </tr>        
</table>