<h1>Confirm Email</h1>
<p>Please check your email and click the link provided to confirm your email.</p>

<?php if($this->logged_in_user): ?>
    <a class="btn btn-primary" href="<?=$this->url(array('module'=>'default','controller'=>'user','action'=>'resend-email-confirmation'));?>">Re-send email confirmation</a>
<?php else: ?>
    <form method="post" action="<?=$this->url(array('module'=>'default','controller'=>'user','action'=>'resend-email-confirmation'));?>" class="form-inline">
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="jane.doe@example.com">
        </div>
        <button type="submit" class="btn btn-primary">Re-send email confirmation</button>
    </form>
<?php endif; ?>