<?php if(!$this->error): ?>
    <h1>Password Reset for <?=$this->user->email_address?></h1>
    <p>Please enter your new password</p>
    <p> </p>
    <?=$this->form?>
<?php else: ?>
<ul>
    <li><a href="<?=$this->url(array('action'=>'login'))?>" title="Login">Login</a></li>
    <li><a href="<?=$this->url(array('action'=>'password-assistance'))?>" title="Password Assistance">Password Reset</a></li>
</ul>
<?php endif; ?>